### ISSUE TITLE
Error installing semantra.

### ISSUE THREAD

**Issue by lhtiger** [freedmand/semantra#1]
hi:

      The following error was found, please help.
----------------------------------------------------------------------------------
Fatal error from pip prevented installation. Full pip output in file:
    C:\Users\lh_ti\.local\pipx\logs\cmd_2023-04-25_15.39.21_pip_errors.log

pip failed to build package:
    annoy-fixed

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

Error installing semantra.
-----------------------------------------------------------------------------------------
![error](https://user-images.githubusercontent.com/17313015/234212983-00e2bffb-d82e-4ed8-99d1-00ce50935672.png)

![visual c++](https://user-images.githubusercontent.com/17313015/234212335-1a21f4f2-313b-4349-a9b4-3d4572ec48df.png)

**Comment by xiqiuqiu** [comment]
It seems that this is not a code error. You may need to install Microsoft's development kit first. The error message indicates that Microsoft Visual C++ needs to be installed beforehand.

**Comment by lhtiger** [comment]
The following image shows the package I installed, and Latest package.

**Comment by lhtiger** [comment]
thanks！

**Comment by yeghub** [comment]
i met the some install error ,@lhtiger ,do  you solved it ?  and how to fix it?

**Comment by lhtiger** [comment]
I installed the ubuntu virtual machine on my own machine and it was successful.

**Comment by Ayman-Fadil** [comment]
Solved it on mac by running:
xcode-select --install

**Comment by freedmand** [comment]
Closing this issue for now since it appears to be unrelated to Semantra itself. If we get enough common installation issues and how to fix them, I can put together a troubleshooting guide. Many thanks!

**Comment by chuaxr** [comment]
I faced some errors when trying to install on windows subsystem on linux but installing gcc and g++ resolved those issues:

```
(research) chuaxr@MSS21701323:~$ pipx install semantra
Fatal error from pip prevented installation. Full pip output in file:
    /home/chuaxr/.local/pipx/logs/cmd_2023-05-04_12.38.19_pip_errors.log

pip failed to build package:
    annoy-fixed

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    error: command 'gcc' failed: No such file or directory
    error: legacy-install-failure
```

```
(research) chuaxr@MSS21701323:~$ pipx install semantra
Fatal error from pip prevented installation. Full pip output in file:
    /home/chuaxr/.local/pipx/logs/cmd_2023-05-04_12.49.24_pip_errors.log

pip failed to build package:
    annoy-fixed

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    gcc: fatal error: cannot execute ‘cc1plus’: execvp: No such file or directory
    error: command '/usr/bin/gcc' failed with exit code 1
    error: legacy-install-failure
```

**Comment by Jaifroid** [comment]
I get the same error attempting to install on Windows in PowerShell, i.e. `Microsoft Visual C++ 14.0 or greater is required`. However, the Visual C++ package is already installed.

I'm happy to run it in WSL, but perhaps lack of compatibility with Windows per se should be flagged in the README.
