### ISSUE TITLE
Location of the index

### ISSUE THREAD

**Issue by martoiu** [freedmand/semantra#26]
Is it possible to choose another location for the indexes? Now Semantra seems to write the data in the User directory on Windows. I regularily restore images of the C: drive, thus the indexes will get lost. Moreover, I want to keep the data on C: as small as possible.

**Comment by freedmand** [comment]
Yes, it is possible. I probably should write a guide for this. Run `semantra --show-semantra-dir` to see where the current index location is, and `semantra --semantra-dir [folder] <rest_of_command>` to change it.
