### ISSUE TITLE
Embedding Cache Location and Custom Path Specification during Initialization

### ISSUE THREAD

**Issue by NTUYi** [freedmand/semantra#27]
I am opening this issue to inquire about the location of the embedding cache and whether it's possible to specify a custom path during initialization. This would be helpful for backing up the cache and preventing accidental deletion. Any guidance on this matter would be appreciated.

**Comment by freedmand** [comment]
On my list to document this better, but check out this recent closed issue where I discuss how to specify and see where the cache directory is: https://github.com/freedmand/semantra/issues/26#issuecomment-1529719694

**Comment by NTUYi** [comment]
That's exactly what I want. Great thx
