### ISSUE TITLE
请问能否增强对中文的支持？

### ISSUE THREAD

**Issue by cloudtuotuo** [freedmand/semantra#30]
希望能更好的支持中文语义检索

**Comment by hiflychat** [comment]
引入，中文嵌入模型就可以了，例如：semantra --transformer-model shibing624/text2vec-base-chinese <filenames>

**Comment by hiflychat** [comment]
“semantra --transformer-model shibing624/text2vec-base-chinese <filenames>“

**Comment by cloudtuotuo** [comment]
> 引入，中文嵌入模型就可以了，例如：semantra --transformer-model shibing624/text2vec-base-chinese ”filenames“（使用时去掉引号）

试过了，也试了large的模型，效果依然不是很理想。。。没关系，继续期待更好的

**Comment by yych42** [comment]
> Would anyone be interested in contributing a guide written in Chinese on using Semantra with Chinese models?

I'm exploring different models. I will post some results here soon.

**Comment by yych42** [comment]
@cloudtuotuo @hiflychat 你们试过openai的ada 02吗？效果怎么样？

**Comment by cloudtuotuo** [comment]
> Would anyone be interested in contributing a guide written in Chinese on using Semantra with Chinese models?

Just translate README.md or write a new one like this (https://zhuanlan.zhihu.com/p/624842644) ?

**Comment by cloudtuotuo** [comment]
> 我的本地机性能很普通（12代i7），显卡都是集成的，所以大型模型都没有尝试

**Comment by yych42** [comment]
> 我的本地机性能很普通（12代i7），显卡都是集成的，所以大型模型都没有尝试

了解。我昨天大概看了一下，现在中文还没有特别好的嵌入模型。E5最近可能会出一个多语言版本。到时候我争取部署一个和openai api兼容的服务。

@freedmand there’s no particularly strong Chinese embedding model yet. Existing models are probably unusable for semantra’s purposes.  E5 [might](https://github.com/microsoft/unilm/issues/1069) release a multilingual version soon. Can you keep this issue open? I’ll keep following up here.

**Comment by freedmand** [comment]
Sounds good, thanks for looking into it! Wow, multilingual E5 will be great!

**Comment by yych42** [comment]
It seems E5 quietly released the multilingual weights the same day we were talking about it. 

https://huggingface.co/intfloat/multilingual-e5-base

will look into it and write up an update here.

**Comment by yych42** [comment]
Short update:
It works out-of-the-box with `semantra --transformer-model intfloat/multilingual-e5-base [files]` and the querying results are reasonably well with the file I tested (see below for a few examples).

Speed might be a drawback. A 63-page Chinese document took just about 1 minute to embed in Debian via OrbStack on M1 Pro. But I think it's a workable solution for most users.

<img width="682" alt="Screenshot 2023-05-24 at 16 44 13" src="https://github.com/freedmand/semantra/assets/43839115/f2325a16-0
<img width="646" alt="Screenshot 2023-05-24 at 16 44 35" src="https://github.com/freedmand/semantra/assets/43839115/a50b752e-9bd2-49c0-b7d9-69ee102488d9">
228-4da3-97e5-e4dba4839250">
<img width="690" alt="Screenshot 2023-05-24 at 16 45 47" src="https://github.com/freedmand/semantra/assets/43839115/758d6222-6fcd-4953-99ec-aa9d690cb438">

**Comment by BruceChen7** [comment]
> 简短更新： 使用 semantra --transformer-model intfloat/multilingual-e5-base [文件]，它可以开箱即用，并且我测试的文件查询结果相当不错（如下面的一些示例所示）。
> 
> 速度可能是一个缺点。在 M1 Pro 的 OrbStack 上，一份 63 页的中文文件在 Debian 中嵌入大约需要 1 分钟。但我认为这对大多数用户来说是一个可行的解决方案。
> 
> Short update: It works out-of-the-box with `semantra --transformer-model intfloat/multilingual-e5-base [files]` and the querying results are reasonably well with the file I tested (see below for a few examples). 它开箱即用，查询结果与我测试的文件相当好（见下面的几个例子）。
> 
> Speed might be a drawback. A 63-page Chinese document took just about 1 minute to embed in Debian via OrbStack on M1 Pro. But I think it's a workable solution for most users.速度可能是一个缺点。通过 M1 Pro 上的 OrbStack 将一份 63 页的中文文档仅用了大约 1 分钟的时间嵌入到 Debian 中。但我认为这对大多数用户来说是一个可行的解决方案。
> <img alt="Screenshot 2023-05-24 at 16 44 13" width="682" src="https://user-images.githubusercontent.com/43839115/240646522-f2325a16-0228-4da3-97e5-e4dba4839250.png"> <img alt="Screenshot 2023-05-24 at 16 44 35" width="646" src="https://user-images.githubusercontent.com/43839115/240646549-a50b752e-9bd2-49c0-b7d9-69ee102488d9.png"> <img alt="Screenshot 2023-05-24 at 16 45 47" width="690" src="https://user-images.githubusercontent.com/43839115/240646597-758d6222-6fcd-4953-99ec-aa9d690cb438.png">

感谢，使用该模型后，效果的确可以

**Comment by yych42** [comment]
@freedmand Since e5 seems to work well, I will add a Chinese guide to semantra. I'm thinking about just translating the readme.md. Do you think there's something else I should translate? You can remove the help wanted tag from this issue and assign it to me!

Also, I would love to contribute to v0.2. Are you planning to set up something like a Slack channel for contributors? I can help with that too. Or I can just create an issue and tag you to assign it to me 😄

**Comment by freedmand** [comment]
Thanks, @yych42! I really appreciate all the help on this. Translating the README.md would be fantastic. I was originally thinking a separate guide document would be easier showcasing good settings for running Semantra in Chinese, but README is great if it's not too heavy a lift.

For v0.2, I'm in a pretty exploratory phase at the moment. I think a lot of Semantra will have to be rebuilt, but in a way that's much more modular, maintainable, testable, etc. I'm close to being ready for help and contributions. I'll probably set up a feature branch soon once I've nailed down a few things on the strucutre. I haven't thought about a channel for contributors but that's a really good idea! I'll look into setting something up this weekend.

**Comment by geigerX** [comment]
> semantra --transformer-model intfloat/multilingual-e5-base [files]

@yych42 没用过hf的模型，请问这条命令的[files]要替换成什么？

**Comment by yych42** [comment]
> > semantra --transformer-model intfloat/multilingual-e5-base [files]
> 
> @yych42 没用过hf的模型，请问这条命令的[files]要替换成什么？

单个或者多个文件的本地地址，或者某个目录+通配符

比如

semantra --transformer-model intfloat/multilingual-e5-base /users/yych/desktop/some.pdf /users/yych/downloads/another.pdf

或者

semantra --transformer-model intfloat/multilingual-e5-base /users/yych/documents/*.txt
