### ISSUE TITLE
OSError: sentence-transformers/all-mpnet-base-v2 is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'

### ISSUE THREAD

**Issue by xiaojun2sheng** [freedmand/semantra#32]
OSError: sentence-transformers/all-mpnet-base-v2 is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass `use_auth_token=True`.

**Comment by freedmand** [comment]
This is not on Semantra's end. It looks like Huggingface and Github have had intermittent issues. You should not need to log in to anything. I would keep trying, and hopefully the services will be operational soon.

https://status.huggingface.co/
https://www.githubstatus.com/

<img width="903" alt="image" src="https://github.com/freedmand/semantra/assets/306095/b986ebec-c8a4-4786-ac1e-46717cacf572">

<img width="1060" alt="image" src="https://github.com/freedmand/semantra/assets/306095/b4f9a913-6aab-425d-a667-a8c68ab3343c">
