### ISSUE TITLE
Newbie question. I'm not sure how to run the Web UI server without the embedding process.

### ISSUE THREAD

**Issue by 1980Dragon** [freedmand/semantra#41]
Hello. 

I've already embedded all the necessary documents, and now I just need to turn on the web UI without going through the embedding process. Even after looking at the --help option, I couldn't find an option for 'running the server without embedding process' and it seems like it only provides options for 'embedding without running the server(--no-server)'. 

I'm sorry for asking such a basic question, but if someone could kindly provide an answer, I would greatly appreciate it. (I understand that it might be a well-known method that doesn't require explanation, but as a true beginner, I need the explanation.) 

Thanks in advance.

**Comment by freedmand** [comment]
Not a newbie question at all! Right now the program is tightly coupled so you pass it files, it embeds them if it hasn't already, and then it launches a webserver (all in a single call). Semantra never duplicates work embedding files, so when you run it subsequent times it is not re-embedding the documents — it's just loading the already embedded documents. After that it launches the server.

That said, and as pointed out by [other issues](https://github.com/freedmand/semantra/issues/13), this isn't the best design. I'm working on a v0.2 of Semantra to be less tightly coupled. You can see the goals of this rewrite outlined here: https://github.com/freedmand/semantra/milestone/1

**Comment by 1980Dragon** [comment]
Oh, thank you for your response. I understand now. I appreciate you sharing your impressive project, and I will consider this issue closed. Thank you once again!
