### ISSUE TITLE
"An attempt was made to access a socket in a way forbidden by its access permissions"

### ISSUE THREAD

**Issue by endolith** [freedmand/semantra#47]
I'm getting this on both Windows computers I tried Semantra on.  It apparently means that the default port is already in use?  Can it provide a more helpful error message or just try a different fallback port automatically?

**Comment by freedmand** [comment]
That usually means something else is using the current port (or you have two instances of Semantra running with default args). Automatically trying other ports is a good idea. In the meantime you can specify `--port` followed by a number to customize it per command invocation.

**Comment by endolith** [comment]
Can it at least print a more helpful error message, though?  (`This usually means something else is using the current port; you can specify --port followed by a number to customize it`)

**Comment by freedmand** [comment]
Fixed by #52 and released in v0.1.7. Upgrade by running `pipx upgrade semantra`.

The error message will now be more friendly. Appreciate it!
