### ISSUE TITLE
System-wide .env

### ISSUE THREAD

**Issue by endolith** [freedmand/semantra#48]
https://github.com/freedmand/semantra/blob/main/docs/guide_openai.md

> Semantra will look in the .env file in the directory it's run in and load the environment variable if found.

Which directory is this on Windows?  semantra.exe exists in two places:

- `%USERPROFILE%\.local\bin\semantra.exe`
- `%USERPROFILE%\.local\pipx\venvs\semantra\Scripts\semantra.exe`

But putting the `.env` file in either of these folders does not work.

**Comment by freedmand** [comment]
It will look at whatever your current working directory is when you run Semantra. So if you're running Semantra and your terminal is at your home directory, it might be something like `C:\username`. See [here](https://harshkapadia2.github.io/cli/cmd.html#:~:text=Current%20working%20directory%20(cwd),cmd%20is%20currently%20pointing%20to.&text=The%20cd%20command%20without%20any,in%20the%20%CD%25%20variable.) for more info on current working directory in Windows.

**Comment by endolith** [comment]
Ah, so I need to create a folder for Semantra that contains the .env and then run it from that folder?  Even though pipx makes it so I can run semantra from any folder?  Can there be a profile-wide .env instead?

**Comment by freedmand** [comment]
Fixed by #52 and released in v0.1.7. Upgrade by running `pipx upgrade semantra`.

You can now create a `.env` file in the Semantra directory that will work globally wherever you run the command. You can reveal this directory by running `semantra --show-semantra-dir`.
