### ISSUE TITLE
 No such option: --query_token_pre

### ISSUE THREAD

**Issue by Kedaranatha** [freedmand/semantra#60]
im following instructions to load (venv) PS D:\AI\Semantra> semantra --transformer-model Muennighoff/SGPT-1.3B-weightedmean-msmarco-specb-bitfit --query_token_pre='[' --query_token_post=']' --doc_token_pre='{' --doc_token_post='}' url

but getting error:

Usage: semantra [OPTIONS] [FILENAME]...
Try 'semantra --help' for help.

Error: No such option: --query_token_pre (Possible options: --doc-token-pre, --query-token-post, --query-token-pre)

windows 11

**Comment by freedmand** [comment]
Can you try running `--query-token-pre` with hyphens instead of underscores?
