### ISSUE TITLE
Failed to install with pipx

### ISSUE THREAD

**Issue by kilasuelika** [freedmand/semantra#64]
Reason:
```
pipx install semantra

No apps associated with package semantra or its dependencies. If you are attempting to install a library, pipx should not be used. Consider using
pip or a similar tool instead.
```
I also tried to install using pip install. The package is installed but semantra command is not found when run in cmd.

**Comment by dylanhogg** [comment]
I got the same "No apps associated" issue with pipx.

Installing in it's own venv on OSX worked well however:
```
python3 -m venv venv
source venv/bin/activate
pip install semantra
semantra "my file.pdf"
```

**Comment by freedmand** [comment]
Strange. I can't replicate but I will add this advice to the README. Thanks for sharing how to solve it
