### ISSUE TITLE
How to migrate to different computer?

### ISSUE THREAD

**Issue by kindofausername** [freedmand/semantra#65]
I want to migrate my semantra to a different computer but don't want to reembed all documents again.

**Comment by freedmand** [comment]
Hi @kindofausername, you can migrate from computer A to computer B by doing the following:

Computer A:
```
semantra --show-semantra-dir
```

This will print the directory in which Semantra is storing all its files.

On computer B, install Semantra and run the same command: `semantra --show-semantra-dir`. Then you can migrate the files by simply copying them from computer A's directory to computer B's directory.
