### ISSUE TITLE
Colab and Languages

### ISSUE THREAD

**Issue by Erickfeio** [freedmand/semantra#7]
Hey, there! Is it possible to run this on google colab? And does this support other languages, like portuguese?

**Comment by cam-rodriguez** [comment]
I'm (tentatively) getting it to run on CoLab right now

**Comment by freedmand** [comment]
I'm interested to hear how the CoLab exploration goes.

Re: running it in Portuguese, you can use any custom model on Hugging Face. For example, this model looks relevant https://huggingface.co/ruanchaves/bert-large-portuguese-cased-assin2-similarity. You can run it via `semantra --transformer-model ruanchaves/bert-large-portuguese-cased-assin2-similarity <documents>`

**Comment by freedmand** [comment]
Closing for now. Feel free to reopen if there's a specific feature request or guide to getting it to run in CoLab. Thanks!
